# Generated by Django 4.0 on 2021-12-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_fee',
            field=models.IntegerField(null=True),
        ),
    ]
