# Generated by Django 4.0 on 2021-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(default='ade', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='add', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
