# Generated by Django 4.0 on 2022-01-07 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productreview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 19, 24, 20, 111980)),
        ),
    ]
