# Generated by Django 4.0 on 2022-01-10 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productreview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
