# Generated by Django 4.0 on 2021-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image_detail_product_image_introduce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_bool',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
