# Generated by Django 4.0 on 2022-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='question_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='question_body',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
