# Generated by Django 4.0 on 2021-12-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_option_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option5',
        ),
    ]
