# Generated by Django 4.0 on 2021-12-22 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_option1_remove_product_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
