# Generated by Django 4.0 on 2022-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productquestion_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='question_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='question_state',
            field=models.BooleanField(default=False),
        ),
    ]
