# Generated by Django 4.0 on 2021-12-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_option1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op2', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op1', to='store.product'),
        ),
    ]
