# Generated by Django 4.0 on 2021-12-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_option2_alter_product_option1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op3', to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='option4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op4', to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='option5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op5', to='store.product'),
        ),
    ]
