# Generated by Django 4.0 on 2022-01-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productreview_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='customer_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
