# Generated by Django 4.0 on 2021-12-22 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_option3_product_option4_product_option5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op1', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op2', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op3', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op4', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op5', to='store.product'),
        ),
    ]
