# Generated by Django 4.0 on 2022-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
