# Generated by Django 4.0 on 2022-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productreview_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
