# Generated by Django 4.0 on 2021-12-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_option1_alter_product_option2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='traking_number',
            new_name='track_number',
        ),
    ]
