# Generated by Django 4.0 on 2022-01-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreview_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='review_user_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
