# Generated by Django 4.0 on 2021-12-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_traking_number_order_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
