# Generated by Django 4.0 on 2022-01-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productquestion_review_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
