# Generated by Django 4.0 on 2022-01-22 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_productquestion_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
