# Generated by Django 4.0 on 2021-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_carosel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosel',
            name='href',
            field=models.CharField(default='#', max_length=200, null=True),
        ),
    ]
