# Generated by Django 4.0 on 2022-01-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productquestion_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option_total',
        ),
    ]
