# Generated by Django 4.0 on 2021-12-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_bool',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
