# Generated by Django 4.0.1 on 2022-02-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_price_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order_item_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem')),
                ('product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productoption')),
            ],
        ),
    ]
