# Generated by Django 4.0.1 on 2022-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitemoption_item_option_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemoption',
            name='item_option_bool',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_option_bool',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
