# Generated by Django 4.0 on 2021-12-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
    ]
