# Generated by Django 4.0 on 2021-12-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_address1_customer_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_request',
            field=models.CharField(default='빨리 배달 해주세요', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(default='홍성우', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_number',
            field=models.CharField(default='010-1234-1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipent_address1',
            field=models.CharField(default='recipent_address1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipent_address2',
            field=models.CharField(default='recipent_address2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipent_name',
            field=models.CharField(default='받는사람이름', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipent_number',
            field=models.CharField(default='010-2323-2321', max_length=50),
            preserve_default=False,
        ),
    ]
