# Generated by Django 4.0.1 on 2022-02-19 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_orderitemoption_item_option_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='order_item_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productoption'),
        ),
    ]
