# Generated by Django 4.0.1 on 2022-02-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_address1_remove_customer_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
