# Generated by Django 4.0 on 2021-12-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_order_request_order_orderer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
