# Generated by Django 4.0 on 2021-12-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_customer_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mileage',
        ),
    ]
