# Generated by Django 4.0 on 2021-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_customer_address1_remove_customer_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(default='dsfsdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='adfasf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('M', 'Female'), ('N', 'Unknown')], default='dasfsadf', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateField(default='asdfasf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mileage',
            field=models.IntegerField(default='asdfasdf'),
            preserve_default=False,
        ),
    ]
