# Generated by Django 4.0 on 2021-12-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_customer_address1_customer_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mileage',
        ),
    ]
