# Generated by Django 4.0 on 2021-12-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_customer_join_date_remove_customer_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
