# Generated by Django 3.2.12 on 2022-02-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20220226_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='emb_pg_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='imp_uid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='track_number',
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('order_status', models.BooleanField(default=False)),
                ('payment_state', models.BooleanField(default=False)),
                ('shipping_fee', models.IntegerField(blank=True, null=True)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
                ('post_code', models.CharField(blank=True, max_length=200, null=True)),
                ('recipent_address1', models.CharField(max_length=200)),
                ('recipent_address2', models.CharField(max_length=200)),
                ('recipent_number', models.CharField(max_length=50)),
                ('recipent_name', models.CharField(max_length=50)),
                ('order_request', models.CharField(max_length=100)),
                ('orderer_number', models.CharField(max_length=100)),
                ('orderer_name', models.CharField(max_length=100)),
                ('receipt_url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('emb_pg_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('imp_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_method', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
    ]
