# Generated by Django 3.2.12 on 2022-02-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220228_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_status',
        ),
    ]
