# Generated by Django 3.2.12 on 2022-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_orderhistory_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_name',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
