# Generated by Django 3.2.12 on 2022-02-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_orderhistory_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
