# Generated by Django 3.2.12 on 2022-03-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_orderhistory_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderhistory'),
        ),
    ]
