# Generated by Django 3.2.12 on 2022-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_orderitem_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
