# Generated by Django 3.2.12 on 2022-03-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_orderhistory_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_state',
            new_name='deliver_state',
        ),
    ]
