# Generated by Django 3.2.12 on 2022-03-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_orderitem_deliver_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='deliver_state',
        ),
    ]
