# Generated by Django 3.2.12 on 2022-03-03 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAExchangeRefundList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqstExrfn', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('date_sent', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('orderItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
            ],
        ),
    ]
