# Generated by Django 3.2.12 on 2022-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20220316_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deliver_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
