# Generated by Django 3.2.12 on 2022-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20220321_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allowPromotions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
