# Generated by Django 3.2.12 on 2022-03-23 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_productreview_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
