# Generated by Django 3.2.12 on 2022-03-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_productreview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
